spring.application.name=ai-project-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_project_manager_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8089

application.security.jwt.secret-key=Lorem_ipsum_dolor_sit_amet,_consectetuer_adipiscing_elit._Ae_256
application.security.jwt.expiration=86400000